---
name: R-CMD-check
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      # This allows installation of private github repos
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::devtools
            uclahs-cds/private-R-BoutrosLab-statistics-general@9d33f65
          needs: check
      - uses: r-lib/actions/check-r-package
        env:
          _R_CHECK_FORCE_SUGGESTS_: false
        with:
          args: 'c("--no-manual", "--as-cran")'
