---
name: R-CMD-check
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      # This allows installation of private github repos
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install private packages
        run: install.packages('remotes'); remotes::install_github('uclahs-cds/public-R-BoutrosLab-plotting-general')
        shell: Rscript {0}
