
---
name: R-CMD-check
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      # This allows installation of private github repos
      GITHUB_PAT: ${{ secrets.PAT }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install BL
        run: install.packages('remotes'); remotes::install_github('uclahs-cds/private-R-BoutrosLab-utilities@5dc38fbe5fb'); remotes::install_github('uclahs-cds/private-R-BoutrosLab-statistics-general@9d33f65a3b')
        shell: Rscript {0}
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: devel
          extra-packages: |
            any::rcmdcheck
            any::devtools
            BoutrosLab.utilities=?ignore
            BoutrosLab.statistics.general=?ignore
          needs: check
      - name: Document roxygen2
        run: devtools::document()
        shell: Rscript {0}
      - uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual", "--as-cran")'
